name: CI
on: [push, pull_request]
env:
  CI: some-string-to-make-tests-run-without-watching
jobs:
  unit_tests:
    name: 'Unit tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            .eslintcache
            ~/.npm
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: 'Install'
        run: npm install
      - name: 'Test'
        run: npm test
